= Работаем в тестовом лабораторном проекте

Проблема, в структуре проекта.
Одна из особенностей, в том, что я не хочу делать EAR.
Я хочу отдельно деплоить только EJB и только WAR.
И вот тут-то и начинаются проблемы по найстроке и Мавена и проектов в целом.

после прочтения (этого)[https://stackoverflow.com/questions/4441237/packaging-ejb-in-javaee-6-war-vs-ear]
я понял что. просто так вот разделить и по отдельности деплоить не получится....
Надо генерить именно EAR проект...

по итогу хорошая структура мавен проектов я смотрю отсюда https://stackoverflow.com/a/32991219/1679702

Что-то под конец дня, все эти структуры вообще не работают :( у меня опять уныние от этого

== Итоги

Короче, у меня получилось запустить этот проект.

=== Мои ошибки:
1. Оказывается невозможно раздельно положить проект EJB и WAR ручками. +
Двумя деплоями. Это просто невозможно.
Необходимо создавать EAR проект.
1. Как оказалось, EAR проект с мавеном нужно правильно настроить *pom* файл. +
В разделе <dependancy> неоходимо указывать <type>, без него не будет тут собираться правильно проект.

=== Выводы:
А их по сути еще нет. Почему? Потому что, да я увидел, EJB индектится в контроллер JSF.
Да у нас есть разделение, логики и представления. Но у нас нет интерфейсов удаленных на EJB,
и все болтается рядышком. А следовательно можно все запихать в один толстый WAR.
Как у нас в проекте рабочем и созданно...

Но на самом деле, меня манит возможность подключиться к EJB удаленно, клиентом например
А не только через веб-мордашку. Например можно десктопныйы клиент написать.
Интересно насколько это оправданно или красиво?
